### ISSUE TITLE
install FindLiandui for Gilbert

### ISSUE THREAD

**Issue by GoogleCodeExporter** [yancyn/misc#55]
```
probably due to missing some .net framework.
```

Original issue reported on code.google.com by `yancyn@gmail.com` on 16 Jan 2013 at 5:34

**Comment by yancyn** [comment]
This already backup to google spreadhsheet thus app no longer required see https://docs.google.com/spreadsheets/d/1JKtLLmY7G_goTnEdL9AKvlY0VF8JPhbxf75N-Y2mFso/edit?usp=sharing.
